= peacetrue-core

peacetrue-core 是一个 JavaScript 工具类库，提供一些常用接口的实现，如果一些知名类库（如：`lodash`）已经提供了，会给出参考地址。

== 接口绪论

作为程序员，接口是我们得以构建软件的基础。能够多么灵活快速的使用接口，决定着我们的工作效率。

理想情况下，我们希望，在我们需要的时候，就能有可用的接口，并且能简单快速地应用于项目中。

现实情况下，我们会遇到一些困难：

* 有时候 SDK 没有提供需要的接口
* SDK 没有提供时，不得不去网上查找一些知名类库
** 学习知名类库的接口
** 从中找出满足需要的
* 重新实现接口。没有程序员想要重复造轮子，虽然知道一些知名类库可能已经实现了，但查找时间甚至大于重新实现时间

如果能有一个全球统一的接口平台，大家都在上面发布自己的接口，专业人员规范化相似的接口使之成为标准，这样也许能解决我们的困难，但现实是目前还没有。

那么在目前情况下，如何能快速找出想要的接口呢？首先，在抽象层面构建一个语言无关的接口体系，合理分类，不断完善；然后关联不同语言的具体实现，可能有一些尚无具体实现而另一些有多种实现，对于尚无具体实现的，需要自己实现；能够用准确而专业的术语描述出接口对于通过英文查找会有帮助。

//软件世界有各种各样的语言，类、方法、函数更是数之不尽，我们无法记下这么多，也没有必要。
//在我们或漫长或短暂的职业生涯中，掌握更多的接口能提升开发速度和质量。软件世界有各种各样的语言，类、方法、函数更是数之不尽，那么如何合理高效地找到需要的接口呢？

== 对象

归类与对象相关的接口。

=== 获取所有属性名

.javascript
[source%nowrap,javascript]
----
Object.keys({a:'a',b:'b'}) = ["a", "b"]
//属性名顺序与对象中书写顺序一致
----

=== 获取所有属性值

.javascript
[source%nowrap,javascript]
----
Object.values({a:'a',b:'b'}) = ["a", "b"]
//属性值顺序与对象书写顺序一致
----

=== 获取指定属性值

如果仅需要部分属性值或者默认顺序不是想要的，可以通过属性名列表指定。

.javascript
[source%nowrap,javascript]
----
import { values } from 'peacetrue-core';
values({a:'a',b:'b'}) = ["a", "b"]
----

[[从数组构建对象]]
=== 从数组构建对象

通过属性名数组和属性值数组构建对象，通过数组索引关联配对。

.javascript
[source%nowrap,javascript]
----
import { fromArray } from 'peacetrue-core';
fromArray(
['name', 'sex', 'age'],
['张三',  '男',    18 ]
) = {name: '张三', sex: '男', age: 18}
----

== 集合

=== 去重

=== 排序

=== 交集

=== 差集

=== 并集

=== 将数组中的元素从数组转为对象

此方法是 <<从数组构建对象>> 的集合版本。

.javascript
[source%nowrap,javascript]
----
import { elementToObject } from 'peacetrue-core';
let persons = [
      ['张三', 18],
      ['李四', 19],
];
let exceptedPersons = [
  { name: '张三', age: 18 },
  { name: '李四', age: 19 },
];
----


=== 矩阵沿顶角翻转

矩阵指二维数组，型似表格，使用 `matrix` 表示；顶角翻转指以顶点为轴心进行翻转（非旋转），使用 `pivot` 表示。

对以下矩阵（表格）：

|===
|姓名 |性别 |年龄
|张三|男|18
|李四|女|18
|===

沿顶角 *姓名* 翻转后得到：

|===
|姓名 |张三 |李四
|性别 |男 |女
|年龄 |18 |18
|===

其实现过程如下：

暂无图，求 GIF 动图。
//TODO 暂无图，求 GIF 动图。

笔者遇到一个从 Excel 中导入数据的场景，客户的数据使用第一列作为表头，此时需要使用此方法做转换。

方法签名::
pivotMatrix(rows: Array<Array<any>>): Array<Array<any>>

== 场景分析

当我们导出 excel 时，需要将对象集合数据转换为矩阵数据。通常从服务端返回如下格式的 JSON 数据：

.人员列表
[source%nowrap,json]
----
[
  {
    "name": "张三",
    "sex": "男",
    "age": 18
  },
  {
    "name": "李四",
    "sex": "女",
    "age": 18
  }
]
----

需要将其转换为如下格式的矩阵数据：

[source%nowrap,json]
----
[
    ["张三","男",18]
    ["李四","女",18]
]
----

按照 `name、sex、age` 排列。

////

## 问题

### `tsdx lint` 时的一些错误

```
1:9  error  Replace `fromArray,·values` with `·fromArray,·values·`  prettier/prettier
24:3  error  Delete `··`                                             prettier/prettier
25:1  error  Delete `··`                                             prettier/prettier
```

原因是 idea 的格式化使用 4 个空格做缩进，prettier 使用 2 个空格，使用 `yarn run lint --fix` 解决，然后避免手动执行 idea 的 format。


////
